### ISSUE TITLE
IOException when disconnecting while sending an activity

### ISSUE THREAD

**Issue by Almighty-Alpaca** [cbyrneee/KDiscordIPC#15]
This exception is thrown inside a Flow, which means there's no way to handle or ignore it as a user.
```kt
	java.io.IOException: The pipe is being closed
	at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
	at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:546)
	at dev.cbyrne.kdiscordipc.core.socket.impl.WindowsSocket.write(WindowsSocket.kt:48)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invokeSuspend(SocketHandler.kt:52)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invoke(SocketHandler.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invoke(SocketHandler.kt)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Collect.kt:136)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by caoimhebyrne** [comment]
I believe that this was fixed in the latest commit on `dev`, 2b18392 but I'm not 100% sure. If it isn't, let me know. I was getting a `SocketException` on macOS trying to do this but there might be different behavior due to `RandomAccessFile` on Windows
