### ISSUE TITLE
Failed to read raw packet exception on Windows

### ISSUE THREAD

**Issue by Wyvest** [cbyrneee/KDiscordIPC#6]
some users are getting this error:
```
[10:35:41] [Thread-39/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: Failed to read raw packet
[10:35:41] [Thread-39/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.cbyrne.kdiscordipc.socket.DiscordSocket.readPacket(DiscordSocket.kt:156)
[10:35:41] [Thread-39/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.cbyrne.kdiscordipc.socket.DiscordSocket.access$readPacket(DiscordSocket.kt:44)
[10:35:41] [Thread-39/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.cbyrne.kdiscordipc.socket.DiscordSocket$connect$1.invoke(DiscordSocket.kt:80)
[10:35:41] [Thread-39/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at dev.cbyrne.kdiscordipc.socket.DiscordSocket$connect$1.invoke(DiscordSocket.kt:78)
[10:35:41] [Thread-39/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

Some don't, some do, the issue is very inconsistent.

**Comment by caoimhebyrne** [comment]
Not enough information. Please provide their OS, discord version and anything else required.

**Comment by Wyvest** [comment]
![image](https://user-images.githubusercontent.com/45589059/133664908-d46ade50-7017-4dad-aa4f-54f0045bb0c2.png)
![image](https://user-images.githubusercontent.com/45589059/133667688-5b447c52-2f26-4109-9d3f-43c92c104852.png)
they're both using windows 1902, maybe that's the issue?

**Comment by Wyvest** [comment]
![image](https://user-images.githubusercontent.com/45589059/133668410-978c8e9c-443f-443e-9be6-c0be4dedd68b.png)
this is one person that doesn't have the issue, i do not think it is a windows 1902 problem anymore

**Comment by caoimhebyrne** [comment]
It's probably an issue with the windows code. I'll check it out soon.

**Comment by cbyrneee** [comment]
Fixed, working on my machine with latest Discord Stable build & Windows 11. Check if it is fixed for your users (also, make sure those on 1902 are updated... please...)

**Comment by caoimhebyrne** [comment]
@Wyvest, fixed on latest commit. Check with your users if it's fixed on their side. Also, those on 19XX should really update to 20XX...

**Comment by Wyvest** [comment]
checked now, with latest commit the issue still is not fixed

**Comment by caoimhebyrne** [comment]
@Wyvest does this happen instantly, or does it happen after a while?

**Comment by caoimhebyrne** [comment]
This appears to be resolved in the latest commit.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/71222289/137956578-548a7635-aaee-404a-b1f9-60ceaf2996db.png">
